### ISSUE TITLE
RTD wiz explorer has mill reference

### ISSUE THREAD

**Issue by kirijiri** [themill/wiz#16]
There are Mill links in: https://wiz.readthedocs.io/en/latest/tools.html

![image](https://user-images.githubusercontent.com/8530378/89458007-2ac71380-d71b-11ea-990d-ea028ff71a70.png)

Since we won't host wiz explorer, even once its open source, we could probably take that page out for now, and link once we have the wiz explorer docs, which should come with setup guides.

**Comment by buddly27** [comment]
I removed the tool documentation for now. We'll add it back when the wiz-explorer project will be public
