### ISSUE TITLE
Add an IRC / chat channel / mailing list

### ISSUE THREAD

**Issue by charlesfleche** [themill/wiz#43]
Hi @buddly27 and @kirijiri ,

So it went like this:
- Hey, do you know how to do `stuff` in Rez ?
- Not sure, let me check
- Ah, I wish `stuff` was simpler
- Hey, look at this cool new environment configuration system, `wiz`
- But but but, I know those guys ! There are cool people !
- And look at the code, it's clean and nice
- And they don't try to mix concepts
- And they use a standard, proven resolver algorithm rather than research their own
- Where is the mailing list ?

Really happy to know that you guys are on this, it's awesome ! I don't think we are ready to move away from Rez, but it's seriously cool to see this repo !

**Comment by buddly27** [comment]
Hey Charles, glad to see you here :)

Yeah a mailing list would be a good idea once we have made the other tools public (by next week hopefully)

**Comment by JeanChristopheMorinRodeoFX** [comment]
Hi! I'm the one who showed @charlesfleche this repo :) Having a mailing list or a slack channel or pretty much anything would be great indeed.

**Comment by buddly27** [comment]
Just added a Google Group, I'll use this channel to announce the release of related tools:
https://groups.google.com/g/wiz-framework

See you guys over there!
